# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c29482528407188d1bb173d1e38f0bb6d6b6a3c28bdd1ddf343c11471fd112cd3569be5b2061b2bca72f65fc853f63cc4c4608efb1f168c416294b686e40098

test:
  secret_key_base: 8d53cf5a1aaf7bae2e124425aec33136b40a32a12c5c358ba396a83b798e74d30dc293a0dc9e6326a5e98e61af6b14af55e43413c8b7595942f72e0d4621078b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
